// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package mapping

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonA17a9c65DecodeEthMappingContractContractMapping(in *jlexer.Lexer, out *TransferParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "to":
			out.To = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		case "from":
			out.From = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping(out *jwriter.Writer, in TransferParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix[1:])
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	if in.From != "" {
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TransferParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TransferParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping1(in *jlexer.Lexer, out *SystemSupply) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "active_supply":
			out.ActiveSupply = uint64(in.Uint64())
		case "user_supply":
			out.UserSupply = uint64(in.Uint64())
		case "fee_supply":
			out.FeeSupply = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping1(out *jwriter.Writer, in SystemSupply) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"active_supply\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ActiveSupply))
	}
	{
		const prefix string = ",\"user_supply\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserSupply))
	}
	{
		const prefix string = ",\"fee_supply\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.FeeSupply))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SystemSupply) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SystemSupply) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping1(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping2(in *jlexer.Lexer, out *RouterContract) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "contract_id":
			out.ContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping2(out *jwriter.Writer, in RouterContract) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RouterContract) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RouterContract) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping2(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping3(in *jlexer.Lexer, out *PublicKeys) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "primary_pub_key":
			out.PrimaryPubKey = string(in.String())
		case "backup_pub_key":
			out.BackupPubKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping3(out *jwriter.Writer, in PublicKeys) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"primary_pub_key\":"
		out.RawString(prefix[1:])
		out.String(string(in.PrimaryPubKey))
	}
	{
		const prefix string = ",\"backup_pub_key\":"
		out.RawString(prefix)
		out.String(string(in.BackupPubKey))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PublicKeys) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PublicKeys) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping3(l, v)
}
// --- EthDeposit ---
func decodeEthDeposit(in *jlexer.Lexer, out *EthDeposit) {
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() { in.Skip(); in.WantComma(); continue }
		switch key {
		case "tx_hash":
			out.TxHash = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		case "sender":
			out.Sender = string(in.String())
		case "instruction":
			out.Instruction = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}

func encodeEthDeposit(out *jwriter.Writer, in EthDeposit) {
	out.RawByte('{')
	out.RawString("\"tx_hash\":")
	out.String(in.TxHash)
	out.RawString(",\"amount\":")
	out.String(in.Amount)
	out.RawString(",\"sender\":")
	out.String(in.Sender)
	out.RawString(",\"instruction\":")
	out.String(in.Instruction)
	out.RawByte('}')
}

func (v EthDeposit) MarshalTinyJSON(w *jwriter.Writer)    { encodeEthDeposit(w, v) }
func (v *EthDeposit) UnmarshalTinyJSON(l *jlexer.Lexer)   { decodeEthDeposit(l, v) }

// --- MapParams (new: deposits array) ---
func decodeMapParams(in *jlexer.Lexer, out *MapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() { if isTopLevel { in.Consumed() }; in.Skip(); return }
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() { in.Skip(); in.WantComma(); continue }
		switch key {
		case "deposits":
			if in.IsNull() { in.Skip(); out.Deposits = nil } else {
				in.Delim('[')
				if out.Deposits == nil {
					if !in.IsDelim(']') { out.Deposits = make([]EthDeposit, 0, 4) } else { out.Deposits = []EthDeposit{} }
				} else { out.Deposits = (out.Deposits)[:0] }
				for !in.IsDelim(']') {
					var d EthDeposit
					decodeEthDeposit(in, &d)
					out.Deposits = append(out.Deposits, d)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel { in.Consumed() }
}

func encodeMapParams(out *jwriter.Writer, in MapParams) {
	out.RawByte('{')
	out.RawString("\"deposits\":")
	if in.Deposits == nil { out.RawString("null") } else {
		out.RawByte('[')
		for i, d := range in.Deposits {
			if i > 0 { out.RawByte(',') }
			encodeEthDeposit(out, d)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

func (v MapParams) MarshalTinyJSON(w *jwriter.Writer)  { encodeMapParams(w, v) }
func (v *MapParams) UnmarshalTinyJSON(l *jlexer.Lexer) { decodeMapParams(l, v) }

// --- DexInstruction ---
func decodeDexInstruction(in *jlexer.Lexer, out *DexInstruction) {
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() { in.Skip(); in.WantComma(); continue }
		switch key {
		case "type": out.Type = string(in.String())
		case "version": out.Version = string(in.String())
		case "asset_in": out.AssetIn = string(in.String())
		case "asset_out": out.AssetOut = string(in.String())
		case "recipient": out.Recipient = string(in.String())
		case "amount_in": out.AmountIn = string(in.String())
		default: in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}

func encodeDexInstruction(out *jwriter.Writer, in DexInstruction) {
	out.RawByte('{')
	out.RawString("\"type\":"); out.String(in.Type)
	out.RawString(",\"version\":"); out.String(in.Version)
	out.RawString(",\"asset_in\":"); out.String(in.AssetIn)
	out.RawString(",\"asset_out\":"); out.String(in.AssetOut)
	out.RawString(",\"recipient\":"); out.String(in.Recipient)
	out.RawString(",\"amount_in\":"); out.String(in.AmountIn)
	out.RawByte('}')
}

func (v DexInstruction) MarshalTinyJSON(w *jwriter.Writer)  { encodeDexInstruction(w, v) }
func (v *DexInstruction) UnmarshalTinyJSON(l *jlexer.Lexer) { decodeDexInstruction(l, v) }

// --- SwapResult ---
func decodeSwapResult(in *jlexer.Lexer, out *SwapResult) {
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() { in.Skip(); in.WantComma(); continue }
		switch key {
		case "amount_out": out.AmountOut = string(in.String())
		default: in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}

func encodeSwapResult(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	out.RawString("\"amount_out\":"); out.String(in.AmountOut)
	out.RawByte('}')
}

func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer)  { encodeSwapResult(w, v) }
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) { decodeSwapResult(l, v) }
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping5(in *jlexer.Lexer, out *AllowanceParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "spender":
			out.Spender = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping5(out *jwriter.Writer, in AllowanceParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"spender\":"
		out.RawString(prefix[1:])
		out.String(string(in.Spender))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AllowanceParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AllowanceParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping5(l, v)
}
